---
version: '3'
services:
  worker:
    build:
      context: ../../
      dockerfile: Worker.Dockerfile
    hostname: event-stream-worker
    container_name: event-stream-worker
    networks:
      - event-stream-processing_event-stream-processing-network
    environment:
      DOTNET_ENVIRONMENT: Development
      ConsumerOptions:Brokers: broker:9092 
      ProducerOptions:Brokers: broker:9092 
  
networks:
  event-stream-processing_event-stream-processing-network:
    external: true
